<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.6" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.3.9" />
    <PackageReference Include="Microsoft.OpenApi.Readers" Version="1.6.29" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.17.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GivingChampion.Common\GivingChampion.Common.csproj" />
    <ProjectReference Include="..\GivingChampion.Domain\GivingChampion.Domain.csproj" />
    <ProjectReference Include="..\GivingChampion.Infrastructure\GivingChampion.Persistance.csproj" />
  </ItemGroup>

</Project>
