<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>0873da5e-152c-4cf7-9ecd-a4120a22add3</UserSecretsId>
  </PropertyGroup>
	
  <PropertyGroup>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql" Version="13.2.2" />
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.2.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.13.22" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GivingChampion.Application\GivingChampion.Application.csproj" />
    <ProjectReference Include="..\GivingChampion\GivingChampion.ServiceDefaults\GivingChampion.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
