services:
  compose-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    ports:
      - "8090:18888"
    expose:
      - "18889"
      - "18890"
    networks:
      - "aspire"
    restart: "always"
  migrator:
    image: "${MIGRATOR_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ConnectionStrings__DefaultConnection: "${DEFAULTCONNECTION}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "migrator"
    networks:
      - "aspire"
  seeder:
    image: "${SEEDER_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ConnectionStrings__DefaultConnection: "${DEFAULTCONNECTION}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "seeder"
    depends_on:
      migrator:
        condition: "service_completed_successfully"
    networks:
      - "aspire"
  givingchampion-api:
    image: "${API_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${API_PORT}"
      ConnectionStrings__DefaultConnection: "${DEFAULTCONNECTION}"
      Jwt__Issuer: "${JWT_ISSUER}"
      Jwt__Audience: "${JWT_AUDIENCE}"
      Jwt__AccessTokenMinutes: "${JWT_ACCESS_TOKEN_MINUTES}"
      Authentication__Google__ClientId: "${GOOGLE_CLIENT_ID}"
      Authentication__Google__ClientSecret: "${GOOGLE_CLIENT_SECRET}"
      Jwt__Key: "${JWT_KEY}"
      Cors__AllowedOrigins: "${CORS_ORIGINS}"
      Frontend__AuthCallbackUrl: "${AUTH_CALLBACK_URL}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "api"
    ports:
      - "5001:8080"
    labels:
      - "neurix.proxy.domain=champapi.neurix.uk"
      - "neurix.proxy.port=5001"
    expose:
      - "${API_PORT}"
    depends_on:
      seeder:
        condition: "service_completed_successfully"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
